name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run:  |
       python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint code
      run: |
        jupyter nbconvert --to script book.ipynb
        pylint --disable=R,C,E1123,W0104,W0621,W0613 book.py
    - name: Format code
      run: |
        black book.ipynb
